config/routes.rb
Rails.application.routes.draw do
  resources :tx_filters
  resources :tx_filter_details
  get 'transacction_type/dynamic', to: 'transacction_type#dynamic'
  resources :tconfigs
  get 'filtering_categorizations/dynamic', to: 'filtering_categorizations#dynamic'
  # get 'tx_sessions/index'

  get 'transacction_type/index', to: 'transacction_type#index'
  resources :transacction_type #'transacction_type/index', to: 'transacction_type#index'
  resources :tx_sessions
  resources :filtering_categorizations
  resources :states, :path => 'testadosxalerta'
  resources :states
  resources :testadosxalerta
  resources :table_orders
  get 'alert_release/index'
  post 'users/expire', to: 'users#expire'

  get 'users/expire', to: 'users#expire'

  get 'user_priority/index'
  get 'user_priority/assignPriority'
  get 'user_priority/assignPriorityPer'
  get 'user_priority/sessionsTran'
  get 'user_priority/groupsPer'

  get 'niv_alertamiento/index'
  get 'con_gen/index'


  filter :locale

  get 'alertc/par4'
  get 'alertc/par3'
  get 'alertc/par2'
  get 'alertc/par1'
  get 'alertn/histTran'
  get 'alertn/transacciones_alerta'
  get 'home/alertaBoton'
  get 'home/pie3'
  get 'home/pie2'
  get 'home/pie1' #, to: 'home#pie1'
  get 'home/contadorSuperior' #, to: 'home#pie1'
  get 'home/totalAlerts'
  get 'home/alertaTransaccional'
  get 'home/alertaPerfiles'
  get 'home/mensajeAlerta'
  get 'home/totalPoratender'
  get 'home/totalAtendidas'

  get 'chart/empty'
  get 'chart/pies'
  get 'chart/dynamic'

  resources 'chart'


  get 'alertn/alertTran', to: 'alertn#alertTran'
  get 'tbitacora/tbitacora'
  get 'tbitaobse/tbitaobse'
  get 'alertn/alertPer', to: 'alertn#alertPer'
  get 'alertc/busqueda', to: 'alertc#busqueda'

  resources :groups

  resources :views
  resources :profiles
  resources :permissions
  resources :areas
  resources :home
  resources :users
  resources :alertn
  resources :alertc
  resources :con_gen
  resources :chart, only: [:index, :dynamic]
  resources :home, only: [:index, :create]
  resources :mail_groups
  resources :gestor_settings

  ##############################################################################
  ##############################################################################
  ##############################################################################
  ##############################################################################
  # Porcentual
  get 'comparasions/dynamic'
  get 'comparasions/empty'
  get 'comparasions/unselected'
  get 'comparasions/load'

  resources :comparasions

  # get '/:locale' => 'home#index'

  # devise_for :users
  devise_for :users, :controllers => {:registrations => "user/registrations", :sessions => "user/sessions"}, path: 'auth', path_names: {sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in'}
  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      root :to => 'home#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
      resources :expired_accounts
      get "expired_accounts/new"
    end
    get "auth/logout" => "devise/sessions#destroy"
  end
end

app/models/tx_filter.rb
class TxFilter < ApplicationRecord
  belongs_to :tx_session
  has_many :tx_filter_details
end

app/models/tx_filters.rb
class TxFilters < ApplicationRecord
  has_many :tbitacora
  has_many :categori_filters

  #belongs_to :filtering_categorization, foreign_key: :filtering_categorization_id
end

app/controllers/tx_filters_controller.rb
class TxFiltersController < ApplicationController
  before_action :set_tx_filters, only: [:show, :edit, :update, :destroy]

  # GET /tx_filters
  # GET /tx_filters.json
  def index
    @tx_filters = TxFilters.all
  end

  # GET /tx_filters/1
  # GET /tx_filters/1.json
  def show
  end

  # GET /tx_filters/new
  def new
    @tx_filter = TxFilters.new

    tFormatos = Tformatos.all
    gon.formatos = tFormatos

    tCampos = Tcamposformato.all
    gon.tCamposFormatos = tCampos

    tLays = Tcamposlay.all
    gon.tCamposLays = tLays
    gon.false = true
  end

  # GET /tx_filters/1/edit
  def edit

    # Gon para traes los campos del formato y layout correspondiente
    @tx_sessions = TxSessions.all
    tx_sessions = TxSessions.all
    gon.sesiones = tx_sessions

    ## Gon para llenar selects Layout, Formato de ventana modal

    tCampos = Tcamposformato.all
    gon.tCamposFormatos = tCampos

    tLays = Tcamposlay.all
    gon.tCamposLays = tLays
    gon.false = true
  end

  # POST /tx_filters
  # POST /tx_filters.json
  def create

    @idSession = params[:idSession]
    @desFilter = params[:nameFilter]
    @colorFilter = params[:general]
    @typeFilter = params[:typeFilter]

    @tx_filter = TxFilter.new
    @tx_filter.Session_id = @idSession
    @tx_filter.Description = @desFilter
    @tx_filter.Backgroundcolor = @colorFilter
    @tx_filter.Order_number = @typeFilter
    @tx_filter.save


    #// Creacion del filtro
    @detalleFiltro = params[:filtro]
    @idUser = params[:keyId]

    @cont = 0
    @numCondi = 0
    @crearCondicion = false

    @conector
    @negado
    @operador
    @parentesis
    @valor
    @campoFormatoId
    @posision
    @length

    @detalleFiltro.each do | datoFiltro |
      @cont += 1

      if ( @cont === 1 )
        @conector = datoFiltro
      elsif ( @cont === 2 )
        @negado = datoFiltro
      elsif ( @cont === 3 )
        @operador = datoFiltro
      elsif ( @cont === 4 )
        @parentesis = datoFiltro
      elsif ( @cont === 5 )
        @valor = datoFiltro
      elsif ( @cont === 6 )
        @campoFormatoId = datoFiltro
      elsif ( @cont === 7 )
        @posision = datoFiltro
      elsif ( @cont === 8 )
        @length = datoFiltro
        @cont = 0
        @crearCondicion = true
      end

      if ( @crearCondicion  === true )
        @crearCondicion = false
        @numCondi += 1
        # @tx_filter_detail = TxFilterDetail.new(tx_filter_detail_params) marco error enviandolo desde el metodo new de session
        @tx_filter_detail = TxFilterDetail.new
        @tx_filter_detail.filter_id = @tx_filter.id
        @tx_filter_detail.conditionnumber = @numCondi
        @tx_filter_detail.connector = @conector
        @tx_filter_detail.denied = @negado
        @tx_filter_detail.operator = @operador
        @tx_filter_detail.parenthesis = @parentesis
        @tx_filter_detail.value = @valor
        @tx_filter_detail.fieldFormat_id = @campoFormatoId
        @tx_filter_detail.position = @posision
        @tx_filter_detail.lenght = @length
        @tx_filter_detail.key_id = @idUser
        @tx_filter_detail.save
      end
    end

    # @txfilter = TxFilters.new()
    # val1 = params[:Session_id]
    # val2 = params[:Description]
    # val3 = params[:Backgroundcolor]
    # val4 = params[:Order_number]
    # val5 = params[:Key_id]
    #
    # if( params[:_method].present? && params[:_method] == 'create' )
    #   @txfilter.Session_id = params[:Session_id]
    #   @txfilter.Description = params[:Description]
    #   @txfilter.Backgroundcolor = params[:Backgroundcolor]
    #   @txfilter.Order_number = params[:Order_number]
    #   @txfilter.Key_id = params[:Key_id]
    #   @txfilter.save
    #
    #   @tx_filter_detail = TxFilterDetail.where(:filter_id => nil).where(:key_id => current_user.id)
    #   @tx_filter_detail.each do | detalleFiltro|
    #     detalleFiltro.filter_id = @txfilter.id
    #     detalleFiltro.key_id = nil
    #     detalleFiltro.save
    #   end
    # end




    # respond_to do |format|
    #   if @tx_filter.save
    #     format.html { redirect_to @tx_filter, notice: 'Tx filter was successfully created.' }
    #     format.json { render :show, status: :created, location: @tx_filter }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @tx_filter.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /tx_filters/1
  # PATCH/PUT /tx_filters/1.json
  def update
    respond_to do |format|
      if @tx_filter.update(tx_filters_params)
        format.html { redirect_to action: :edit, notice: 'Tx filter was successfully updated.' }
        format.json { render :show, status: :ok, location: @tx_filter }
      else
        format.html { render :edit }
        format.json { render json: @tx_filter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tx_filters/1
  # DELETE /tx_filters/1.json
  def destroy
    @tx_filters.destroy
    respond_to do |format|
      format.html { redirect_to tx_filters_url, notice: 'Tx filter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tx_filters
      @tx_filter = TxFilters.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tx_filters_params
      params.require(:tx_filters).permit(:Id, :Session_id, :Group_id, :Description, :Backgroundcolor, :Lettercolor, :Order_number, :Key_id)
    end
end

app/views/tx_filters/_form.html.erb
<%= stylesheet_link_tag "tx_sessions" %>
<%= stylesheet_link_tag "tx_filters" %>

<%= form_for @tx_filter, :html => {:class => 'form-horizontal', :id => 'form'} do |f| %>
  <% if @tx_filter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tx_filters.errors.count, "error") %> prohibited this tx_filters from being saved:</h2>

      <ul>
        <% tx_filter.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- ## Datos del Filtro ## -->
  <section class="row">
    <article class=" col-lg-5 main_filter">
      <div class="header_filter">
        <h3><%= t('views.tx_filter_index.title') %></h3>
      </div>
      <div class="ibox-content" style="padding: 4em 1em;">
        <div class="row">
          <div class="col-xs-12">
          <% sesionPer = TxSessions.where(:Id => @tx_filter.Session_id) %>
            <% sesionPer.each do | sesion | %>
              <input type="hidden" id="filterSession" value="<%= sesion.Id %>">
              <% if @tx_filter.Session_id == sesion.Id %>
                <p><strong>Este filtro pertenece a la sesion:</strong> <span><%= sesion.Description %></span></p>
              <% else %>
                <p><strong>Este Filtro no perteneces a ninguna sesión</strong></p>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="row filter_description">
          <br>
          <br>
          <div class="col-lg-4"><h4><label class="control-label"><%= t('all.description') %></label></h4></div>
          <div class="col-lg-8">
            <%= f.text_field :Description, id:'des_session', class:'form-control', autocomplete:'off', value:@tx_filter.Description %>
          </div>
        </div>
        <% if @tx_filter.Order_number != 0 %>
        <div class="row filter_color">
          <br>
          <div class="col-lg-4">
            <h4>
              <%= f.label :Backgroundcolor, t('views.tx_filter_new.filter_color') , :id => "colorlabel" %>
            </h4>
          </div>
          <div class="col-lg-8">
            <input type="text" class="form-control demo" name="Backgroundcolor" value="<%= @tx_filter.Backgroundcolor %>" autocomplete="off" />
          </div>
        </div>
        <% end %>
        <div class="row filter_order">
          <br>
          <div class="col-lg-4">
            <h4>
              <label><%= t('views.tx_filter_new.type_filter') %></label>
            </h4>
          </div>
          <div class="col-lg-8">
            <input type="hidden" id="tipoFiltro" value="<%= @tx_filter.Order_number %>">
            <select id="typeFilter" name="type_filter" class="form-control filterSession">
              <option value=""><%= t('views.tx_filter_new.select_type_filter') %></option>
              <option value="0"><%= t('views.tx_filter_new.option_main') %></option>
              <option value="1"><%= t('views.tx_filter_new.option_general') %></option>
              <option value="2"><%= t('views.tx_filter_new.option_group') %></option>
            </select>
          </div>
        </div>
      </div>
    </article>
    <article class=" col-lg-7 main_detalleFiltro">
      <table class="table table-striped table-responsive">
        <thead>
          <tr>
<!--            <th class="text-center"><%#= t('views.tx_filter_detail_new.denied') %></th>-->
            <th class="text-center"><%= t('views.tx_filter_detail_new.connectors') %></th>
            <th class="text-center"><%= t('views.tx_filter_detail_new.expression') %></th>
            <th data-hide="phone, table" class="text-center"><%= t('all.edit') %></th>
          </tr>
        </thead>
        <tbody>
        <% @idFiltro = @tx_filter.Id %>
        <% @detalle = TxFilterDetail.where(:filter_id => @idFiltro) %>

        <% @camposLay = Tcamposlay.all %>

        <% @detalle.each do | condiciones | %>
          <tr class="condicion<%= condiciones.conditionnumber %>">
              <% if (condiciones.denied == "0") %>
                <%# checked = "" %>
                <% no = "" %>
              <% elsif  condiciones.denied == "1"%>
                <%# checked = "checked" %>
                <% no = t('views.tx_filter_detail_new.notPalabra') %>
              <% end %>
            <td class="text-center connector">
              <% if condiciones.connector != "-1" %>
                <span class="btn btn-primary btn-xs changeConector" title="Cambiar conector">
                  <% if condiciones.connector == "0" %>
                    <%= t('views.tx_filter_detail_new.or') %>
                  <% elsif condiciones.connector == "1"  %>
                    <%= t('views.tx_filter_detail_new.and') %>
                  <% end %>
                </span>
              <% end %>
            </td>
            <td class="text-center expresion">
              <strong class="negado"><%= no %></strong>
              <% @idCampoCondi = condiciones.fieldFormat_id %>

              <% @camposLay.each do | camposLay | %>

                <% @idCampoFor = camposLay.IdCampo %>

                <% if ( @idCampoCondi  == @idCampoFor ) %>
                  <% @nombre =  camposLay.Nombre %>
                  <% @alias = camposLay.Alias %>

                  <% if @alias != "" %>
                    <span class="campo" value="<%= @idCampoCondi %>"><%= @alias %></span>
                  <% else %>
                    <span class="campo" value="<%= @idCampoCondi %>"><%= @nombre %></span>
                  <% end %>
                <% end %>
              <% end %>
              <% if condiciones.operator == "0" %>
                <% operador = "=" %>
              <% elsif condiciones.operator == "1" %>
                <% operador = "<>" %>
              <% elsif condiciones.operator == "2" %>
                <% operador = ">" %>
              <% elsif condiciones.operator == "3" %>
                <% operador = ">=" %>
              <% elsif condiciones.operator == "4" %>
                <% operador = "<" %>
              <% elsif condiciones.operator == "5" %>
                <% operador = "<=" %>
              <% elsif condiciones.operator == "6" %>
                <% operador = "Like" %>
              <% elsif condiciones.operator == "7" %>
                <% operador = "In" %>
              <% elsif condiciones.operator == "8" %>
                <% operador = "Between" %>
              <% end %>
              <strong class="operador" value="<%= condiciones.operator %>"><%= operador %></strong>
              <% if condiciones.operator == "8" %>
                <% valores = condiciones.value %>
                <% valorSplit = valores.split("}").join(" ") %>
                <% valoresBetween = valorSplit.split("{") %>
                <span class="valorUno" value="<%= valoresBetween[1] %>"><%= valoresBetween[1] %></span>
                <strong class="conector"><%= t('views.tx_filter_detail_new.and') %></strong>
                <span class="valorDos" value="<%= valoresBetween[2] %>"><%= valoresBetween[2] %></span>
              <% else %>
                <% if condiciones.value == "" %>
                  <span class="parenthesis">
                    <% if condiciones.parenthesis == "1" %>
                      (
                    <% else %>
                      )
                    <% end %>
                  </span>
                <% else  %>
                  <span class="valorUno" value="<%= condiciones.value %>"><%= condiciones.value %></span>
                <% end %>
              <% end %>

            </td>
<!--            <td class="text-center"><a href="/tx_filter_details/<%#= condiciones.id %>/edit" class="btn btn-warning btn-xs"><i class="fa fa-pencil"></i></a></td>-->
            <td class="text-center">
              <button type="button" id="condicion<%= condiciones.id %>"  value="<%= condiciones.id %>" class="btn btn-warning btn-xs  editCondi"  data-toggle="modal" data-target="#modal1" title="<%= t('all.edit') %> <%= t('views.tx_filter_index.condition') %>">
                <i class="fa fa-pencil "></i>
              </button>
            </td>
            <td class="tdDispNone filterCondi conectorVal" value="<%= condiciones.connector %>" name="conector"><%= condiciones.connector %></td>
            <td class="tdDispNone filterCondi denegadoVal" value="<%= condiciones.denied %>" name="denegado"><%= condiciones.denied %></td>
            <td class="tdDispNone filterCondi" value="<%= condiciones.operator %>" name="operador"><%= condiciones.operator %></td>
            <td class="tdDispNone filterCondi parentesisVal" value="<%= condiciones.parenthesis %>" name="parentesis"><%= condiciones.parenthesis %></td>
            <td class="tdDispNone filterCondi" value="<%= condiciones.value %>" name="valor"><%= condiciones.value %></td>
            <td class="tdDispNone filterCondi" value="<%= @idCampoCondi %>" name="campo"><%= @idCampoCondi %></td>
            <td class="tdDispNone filterCondi" value="<%= condiciones.position %>" name="posision"><%= condiciones.position %></td>
            <td class="tdDispNone filterCondi" value="<%= condiciones.lenght %>" name="longitud"><%= condiciones.lenght %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </article>
  </section>
  <!-- ## Final de los datos del Filtro ## -->

  <!-- ##### Modal Edit Condicion #######-->
  <section class="modal fade" id="modal1">
    <div class="modal-size">
      <div class="model-content">

        <!-- Header de la Modal -->
        <div class="modal-header">
          <h1><%= t('all.edit')%> <%= t('views.tx_filter_index.condition') %></h1>
        </div>

        <!-- Contenido de la Modal -->
        <div class="modal-body">
          <input type="hidden" id="idCondicion" name="idCondicion" value="">
          <form action="/tx_filter_details/" method="post" id="formEditCondicion" class="">
            <div class="row">
              <div class="col-lg-1 negadoEdit">
                <label for="" style="display: block"><%= t('views.tx_filter_detail_new.denied') %></label>

              </div>
              <div class="col-lg-1 conectorEdit">
                <label for=""><%= t('views.tx_filter_detail_new.connectors') %></label>
                <div class="connectorEdit">

                </div>
              </div>
              <div class="col-lg-2 campoEdit">
                <label for=""><%= t('views.tx_filter_new.parenthesis') %></label>
                <select name="campoEdit" id="campoEdit" class="form-control">
                  <option value=""><%= t('views.tx_filter_new.parenthesis') %></option>
                </select>
              </div>

              <div class="col-lg-2 operadorEdit">
                <label for=""><%= t('views.tx_filter_detail_new.operators') %></label>
                <select name="operadorEdit" id="operadorEdit" class="form-control">
                  <option value=""><%= t('views.tx_filter_new.parenthesis') %></option>
                  <option value="0"> = </option>
                  <option value="1"> <> </option>
                  <option value="2"> > </option>
                  <option value="3"> >= </option>
                  <option value="4"> < </option>
                  <option value="5"> <= </option>
                  <option value="6"> Like </option>
                  <option value="7"> In </option>
                  <option value="8"> Between </option>
                </select>
              </div>
              <div class="col-lg-3 valuesEdit">
                <label for="" style="display: block;"><%= t('views.tx_filter_detail_new.value') %></label>
                <div class="inputsVal">
                  <input type="text" id="unValor" value="" class="form-control valorUno">
                  <input type="text" id="dosValor" value="" class="form-control valorDos">
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
  <div class="tradu">
    <input type="hidden" id="andPalabra" value="<%= t('views.tx_filter_detail_new.and') %>">
    <input type="hidden" id="orPalabra" value="<%= t('views.tx_filter_detail_new.or') %>">
  </div>
  <!-- Fin de Modal Edit Condicion -->
  <%= f.submit t('all.save'), :class => 'btn btn-primary btn-xs saveEdit' %>
  <%= link_to t('all.back'),  tx_sessions_index_path, :class => 'btn btn-primary btn-xs'  %>
  <%#= button_tag(type: 'submit', class: 'btn btn-primary btn-xs') do %>
<!--    <i class="fa fa-upload"></i> <%#= t('views.mail_group_form.btn_Save') %>-->
  <%# end %>
<% end %>

app/views/tx_filters/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="ibox-title" >
      <h1><%= t('all.edit') %> <%= t('views.tx_filter_index.title') %></h1>
    </div>
    <div class="ibox-content">
      <%= render 'form', tx_filters: @tx_filters %>
<!--      <%#= link_to 'Show', @tx_filters %> |-->
      <%#= link_to t('all.back'), tx_sessions_index_path, class:'btn btn-primary btn-xs' %>
    </div>
  </div>
</div>

app/views/tx_filters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tx Filters</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tx_filters.each do |tx_filters| %>
      <tr>
        <td><%= link_to 'Show', tx_filters %></td>
        <td><%= link_to 'Edit', edit_tx_filters_path(tx_filters) %></td>
        <td><%= link_to 'Destroy', tx_filters, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tx Filters', new_tx_filters_path %>

app/views/tx_filters/new.html.erb
<div class="ibox">
  <div class="ibox-title">
    <h1><%= t('all.new')%> <%= t('views.tx_filter_index.title') %></h1>
  </div>
  <div class="ibox-content">
    <%= render 'form', tx_filters: @tx_filter %>
  </div>
</div>

app/views/tx_filters/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tx_filters_path(@tx_filters) %> |
<%= link_to 'Back', tx_filters_path %>